[package]
name = "roadrunner-server"
version = "0.1.0"
authors = ["Alexandre Frigon <alexandre.frigon.1@gmail.com>"]
edition = "2018"


[dependencies]
core = { path = "../core" }
math = { path = "../math" }
