name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clone core
      run: git clone https://github.com/roadrunner-craft/core ../core
    - name: Clone math
      run: git clone https://github.com/roadrunner-craft/math ../math
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
